# Generated by Django 4.0.4 on 2022-08-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=250)),
                ('date', models.DateField()),
                ('mileage', models.IntegerField()),
                ('repair', models.CharField(default=None, max_length=250)),
                ('next_repair', models.CharField(default=None, max_length=250, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
